#!/bin/bash
# symlinks necessary dotfiles and config files
cd ~/dotfiles
for file in files/.*
do
  filename=$(basename ${file})
  if [[ "$filename" == "." || "$filename" == ".." ]]; then 
      continue 
  fi
  ln -s ~/dotfiles/files/${filename} ~/${filename}
done

# symlink vim things
mkdir -p ~/.config/
ln -s ~/dotfiles/files/nvim ~/.config/nvim
