#!/bin/bash
cd ~/dotfiles
for file in files/.*
do
  filename=$(basename ${file})
  if [[ "$filename" == "." || "$filename" == ".." ]]; then 
      continue 
  fi
  ln -s ~/dotfiles/files/${filename} ~/${filename}
done
